-- Package library (ADR 047, docs/SUPPLIER_OPERATIONS.md): ready-made transfers,
-- sightseeing and activities for popular destinations, kept by the Idea Holiday
-- admin. A supplier adds entries to its own private rate sheet (069), where they
-- become ordinary services it can edit; the library itself is never priced or sold.
--
-- Prices are EXAMPLES the supplier must check: per vehicle for Sedan (4 seats),
-- Innova (6) and Tempo Traveller (12), or per adult and child for an activity.
-- Adding an entry copies them into one season starting that day.

CREATE TABLE IF NOT EXISTS package_library_items (
  id TEXT PRIMARY KEY,
  region TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('TRANSFER', 'SIGHTSEEING', 'ACTIVITY')),
  name TEXT NOT NULL,
  city TEXT,
  from_place TEXT,
  to_place TEXT,
  distance_km INTEGER,
  duration_hours REAL,
  day_title TEXT,
  day_description TEXT,
  sedan_inr INTEGER CHECK (sedan_inr >= 0),
  innova_inr INTEGER CHECK (innova_inr >= 0),
  tempo_inr INTEGER CHECK (tempo_inr >= 0),
  adult_inr INTEGER CHECK (adult_inr >= 0),
  child_inr INTEGER CHECK (child_inr >= 0),
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_package_library_items_region ON package_library_items(status, region, sort_order);

-- Which library entry a supplier's service came from, so it is not added twice.
ALTER TABLE supplier_services ADD COLUMN IF NOT EXISTS library_item_id TEXT;

-- The starter library: Golden Triangle, Uttar Pradesh, Goa, Kerala, Himachal Pradesh,
-- Jammu & Kashmir, Leh Ladakh, Rajasthan and Uttarakhand. Entry fees are for Indian nationals.
INSERT INTO package_library_items (id, region, kind, name, city, from_place, to_place, distance_km, duration_hours, day_title, day_description, sedan_inr, innova_inr, tempo_inr, adult_inr, child_inr, sort_order) VALUES
('plib_gt_01', 'Golden Triangle', 'TRANSFER', 'Delhi Airport to Hotel', 'Delhi', 'Delhi Airport (IGI)', 'Hotel in Delhi', 25, 1.5, 'Arrive in Delhi', 'Our driver meets you at the airport arrivals hall and takes you to your hotel. The rest of the day is free to settle in.', 1500, 2200, 3800, NULL, NULL, 10),
('plib_gt_02', 'Golden Triangle', 'TRANSFER', 'Hotel to Delhi Airport', 'Delhi', 'Hotel in Delhi', 'Delhi Airport (IGI)', 25, 1.5, 'Departure from Delhi', 'After breakfast, check out and transfer to Delhi airport for your onward flight.', 1500, 2200, 3800, NULL, NULL, 20),
('plib_gt_03', 'Golden Triangle', 'SIGHTSEEING', 'Delhi full-day sightseeing', 'Delhi', NULL, NULL, 80, 8, 'Delhi: Old and New Delhi', 'Visit Jama Masjid and ride a rickshaw through Chandni Chowk, then see Raj Ghat, India Gate, Humayun''s Tomb and the Qutub Minar.', 2800, 3800, 6000, NULL, NULL, 30),
('plib_gt_04', 'Golden Triangle', 'TRANSFER', 'Delhi to Agra by car', 'Delhi', 'Delhi', 'Hotel in Agra', 230, 4, 'Delhi to Agra', 'Drive to Agra on the Yamuna Expressway and check in to your hotel.', 4500, 6500, 10000, NULL, NULL, 40),
('plib_gt_05', 'Golden Triangle', 'SIGHTSEEING', 'Agra full-day sightseeing', 'Agra', NULL, NULL, 60, 8, 'Agra: Taj Mahal and Agra Fort', 'See the Taj Mahal, the white marble tomb built by Shah Jahan, then Agra Fort and the Baby Taj (Itimad-ud-Daulah).', 2500, 3500, 5500, NULL, NULL, 50),
('plib_gt_06', 'Golden Triangle', 'TRANSFER', 'Agra to Jaipur via Fatehpur Sikri', 'Agra', 'Hotel in Agra', 'Hotel in Jaipur', 240, 6, 'Agra to Jaipur via Fatehpur Sikri', 'Drive to Jaipur, stopping at Fatehpur Sikri, Akbar''s abandoned red sandstone capital.', 5000, 7000, 11000, NULL, NULL, 60),
('plib_gt_07', 'Golden Triangle', 'SIGHTSEEING', 'Jaipur full-day sightseeing', 'Jaipur', NULL, NULL, 70, 8, 'Jaipur: the Pink City', 'Visit Amber Fort, stop for photos at Hawa Mahal and Jal Mahal, then see the City Palace and Jantar Mantar.', 2500, 3500, 5500, NULL, NULL, 70),
('plib_gt_08', 'Golden Triangle', 'TRANSFER', 'Jaipur to Delhi by car', 'Jaipur', 'Hotel in Jaipur', 'Delhi', 280, 5.5, 'Jaipur to Delhi', 'Drive back to Delhi for your onward journey.', 5500, 7500, 12000, NULL, NULL, 80),
('plib_gt_09', 'Golden Triangle', 'ACTIVITY', 'Taj Mahal entry with mausoleum', 'Agra', NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, 250, 0, 90),
('plib_gt_10', 'Golden Triangle', 'ACTIVITY', 'Agra Fort entry', 'Agra', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, 50, 0, 100),
('plib_gt_11', 'Golden Triangle', 'ACTIVITY', 'Amber Fort entry', 'Jaipur', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, 100, 0, 110),
('plib_gt_12', 'Golden Triangle', 'ACTIVITY', 'Qutub Minar entry', 'Delhi', NULL, NULL, NULL, 1.5, NULL, NULL, NULL, NULL, NULL, 35, 0, 120),
('plib_up_01', 'Uttar Pradesh', 'TRANSFER', 'Lucknow Airport to Hotel', 'Lucknow', 'Lucknow Airport', 'Hotel in Lucknow', 20, 1, 'Arrive in Lucknow', 'Our driver meets you at Lucknow airport and takes you to your hotel. The rest of the day is free.', 1200, 1800, 3200, NULL, NULL, 130),
('plib_up_02', 'Uttar Pradesh', 'SIGHTSEEING', 'Lucknow full-day sightseeing', 'Lucknow', NULL, NULL, 60, 8, 'Lucknow: City of Nawabs', 'See the Bara Imambara and its Bhool Bhulaiya maze, Rumi Darwaza, the Chhota Imambara and the British Residency, then taste Awadhi kebabs and shop for Chikankari in Aminabad.', 2200, 3200, 5000, NULL, NULL, 140),
('plib_up_03', 'Uttar Pradesh', 'TRANSFER', 'Lucknow to Ayodhya by car', 'Lucknow', 'Hotel in Lucknow', 'Hotel in Ayodhya', 135, 3, 'Lucknow to Ayodhya', 'Drive to Ayodhya, the birthplace of Lord Ram, and check in to your hotel.', 3500, 5000, 8000, NULL, NULL, 150),
('plib_up_04', 'Uttar Pradesh', 'SIGHTSEEING', 'Ayodhya temple darshan', 'Ayodhya', NULL, NULL, 40, 6, 'Ayodhya: Ram Mandir darshan', 'Visit the Shri Ram Janmabhoomi Mandir, Hanuman Garhi and Kanak Bhawan, and attend the evening aarti at Ram ki Paidi on the Saryu.', 2000, 3000, 4800, NULL, NULL, 160),
('plib_up_05', 'Uttar Pradesh', 'TRANSFER', 'Ayodhya to Varanasi by car', 'Ayodhya', 'Hotel in Ayodhya', 'Hotel in Varanasi', 210, 5, 'Ayodhya to Varanasi', 'Drive to Varanasi and check in to your hotel.', 4500, 6500, 10000, NULL, NULL, 170),
('plib_up_06', 'Uttar Pradesh', 'TRANSFER', 'Varanasi Airport to Hotel', 'Varanasi', 'Varanasi Airport', 'Hotel in Varanasi', 25, 1, 'Arrive in Varanasi', 'Our driver meets you at Varanasi airport and takes you to your hotel.', 1200, 1800, 3200, NULL, NULL, 180),
('plib_up_07', 'Uttar Pradesh', 'SIGHTSEEING', 'Varanasi temples and Sarnath', 'Varanasi', NULL, NULL, 50, 8, 'Varanasi and Sarnath', 'Visit Kashi Vishwanath Temple and the Kashi Vishwanath Corridor, then drive to Sarnath, where the Buddha gave his first sermon, and see the Dhamek Stupa.', 2200, 3200, 5000, NULL, NULL, 190),
('plib_up_08', 'Uttar Pradesh', 'ACTIVITY', 'Ganga Aarti boat ride', 'Varanasi', NULL, NULL, NULL, 2, 'Varanasi: Ganga Aarti', 'Take a boat on the Ganges at sunset and watch the Ganga Aarti at Dashashwamedh Ghat from the water.', NULL, NULL, NULL, 600, 300, 200),
('plib_up_09', 'Uttar Pradesh', 'TRANSFER', 'Varanasi to Prayagraj by car', 'Varanasi', 'Hotel in Varanasi', 'Hotel in Prayagraj', 125, 3, 'Varanasi to Prayagraj', 'Drive to Prayagraj and visit the Triveni Sangam, where the Ganga, Yamuna and mythical Saraswati meet.', 3200, 4500, 7500, NULL, NULL, 210),
('plib_up_10', 'Uttar Pradesh', 'TRANSFER', 'Agra to Mathura and Vrindavan', 'Agra', 'Hotel in Agra', 'Mathura and Vrindavan', 60, 8, 'Mathura and Vrindavan', 'Visit Shri Krishna Janmabhoomi in Mathura, then Banke Bihari, ISKCON and Prem Mandir in Vrindavan.', 3000, 4200, 6500, NULL, NULL, 220),
('plib_goa_01', 'Goa', 'TRANSFER', 'Goa Airport (Dabolim) to Hotel', 'Goa', 'Dabolim Airport', 'Hotel in Goa', 40, 1.5, 'Arrive in Goa', 'Our driver meets you at Goa airport and takes you to your hotel. Spend the evening on the beach.', 1500, 2200, 3800, NULL, NULL, 230),
('plib_goa_02', 'Goa', 'TRANSFER', 'Mopa Airport to Hotel', 'Goa', 'Mopa Airport (GOX)', 'Hotel in Goa', 50, 1.5, 'Arrive in Goa', 'Our driver meets you at Mopa airport and takes you to your hotel. Spend the evening on the beach.', 2000, 2800, 4500, NULL, NULL, 240),
('plib_goa_03', 'Goa', 'SIGHTSEEING', 'North Goa sightseeing', 'Goa', NULL, NULL, 80, 8, 'North Goa: forts and beaches', 'Visit Fort Aguada, then the beaches of Candolim, Calangute, Baga and Anjuna, ending at Vagator and Chapora Fort at sunset.', 2500, 3500, 5500, NULL, NULL, 250),
('plib_goa_04', 'Goa', 'SIGHTSEEING', 'South Goa sightseeing', 'Goa', NULL, NULL, 90, 8, 'South Goa: churches and quiet beaches', 'See the Basilica of Bom Jesus and Se Cathedral in Old Goa, Mangueshi Temple, Dona Paula viewpoint and Colva beach.', 2800, 3800, 6000, NULL, NULL, 260),
('plib_goa_05', 'Goa', 'ACTIVITY', 'Mandovi river sunset cruise', 'Goa', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 500, 250, 270),
('plib_goa_06', 'Goa', 'ACTIVITY', 'Dudhsagar Falls jeep safari', 'Goa', NULL, NULL, NULL, 6, 'Dudhsagar Falls', 'Take a jeep through Bhagwan Mahavir Wildlife Sanctuary to Dudhsagar Falls, one of India''s tallest waterfalls, and visit a spice plantation on the way back.', NULL, NULL, NULL, 1500, 800, 280),
('plib_ker_01', 'Kerala', 'TRANSFER', 'Kochi Airport to Hotel', 'Kochi', 'Cochin Airport', 'Hotel in Kochi', 40, 1.5, 'Arrive in Kochi', 'Our driver meets you at Cochin airport and takes you to your hotel.', 1500, 2200, 3800, NULL, NULL, 290),
('plib_ker_02', 'Kerala', 'SIGHTSEEING', 'Kochi half-day sightseeing', 'Kochi', NULL, NULL, 40, 4, 'Kochi: Fort Kochi and Mattancherry', 'See the Chinese fishing nets, St. Francis Church, Mattancherry Palace and the Jewish Synagogue in Jew Town.', 1600, 2300, 3800, NULL, NULL, 300),
('plib_ker_03', 'Kerala', 'TRANSFER', 'Kochi to Munnar by car', 'Kochi', 'Hotel in Kochi', 'Hotel in Munnar', 130, 4, 'Kochi to Munnar', 'Drive up into the Western Ghats past the Cheeyappara and Valara waterfalls to Munnar''s tea country.', 3800, 5000, 8000, NULL, NULL, 310),
('plib_ker_04', 'Kerala', 'SIGHTSEEING', 'Munnar full-day sightseeing', 'Munnar', NULL, NULL, 70, 8, 'Munnar: tea gardens', 'Visit Mattupetty Dam, Echo Point, Kundala Lake and the Tea Museum, with tea estate views all day.', 2800, 3800, 6000, NULL, NULL, 320),
('plib_ker_05', 'Kerala', 'ACTIVITY', 'Eravikulam National Park entry', 'Munnar', NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, 200, 150, 330),
('plib_ker_06', 'Kerala', 'TRANSFER', 'Munnar to Thekkady by car', 'Munnar', 'Hotel in Munnar', 'Hotel in Thekkady', 90, 3, 'Munnar to Thekkady', 'Drive through cardamom hills to Thekkady and visit a spice plantation.', 3000, 4200, 6800, NULL, NULL, 340),
('plib_ker_07', 'Kerala', 'TRANSFER', 'Thekkady to Alleppey by car', 'Thekkady', 'Hotel in Thekkady', 'Alleppey houseboat jetty', 140, 4, 'Thekkady to Alleppey', 'Drive to Alleppey and board your houseboat on the backwaters.', 3800, 5000, 8000, NULL, NULL, 350),
('plib_ker_08', 'Kerala', 'ACTIVITY', 'Periyar lake boat ride', 'Thekkady', NULL, NULL, NULL, 1.5, NULL, NULL, NULL, NULL, NULL, 300, 150, 360),
('plib_ker_09', 'Kerala', 'TRANSFER', 'Alleppey to Kochi Airport', 'Alleppey', 'Alleppey', 'Cochin Airport', 85, 2.5, 'Departure from Kochi', 'After breakfast, drive to Cochin airport for your onward flight.', 2500, 3500, 5500, NULL, NULL, 370),
('plib_hp_01', 'Himachal Pradesh', 'TRANSFER', 'Chandigarh to Shimla by car', 'Chandigarh', 'Chandigarh', 'Hotel in Shimla', 115, 3.5, 'Chandigarh to Shimla', 'Drive up the hills to Shimla, the old summer capital of British India, and check in.', 3500, 4800, 8000, NULL, NULL, 380),
('plib_hp_02', 'Himachal Pradesh', 'SIGHTSEEING', 'Shimla, Kufri and Mall Road', 'Shimla', NULL, NULL, 50, 7, 'Shimla and Kufri', 'Drive to Kufri for Himalayan views, then walk the Mall Road and the Ridge and see Christ Church.', 2500, 3500, 5500, NULL, NULL, 390),
('plib_hp_03', 'Himachal Pradesh', 'TRANSFER', 'Shimla to Manali by car', 'Shimla', 'Hotel in Shimla', 'Hotel in Manali', 250, 8, 'Shimla to Manali', 'Drive along the Beas river through Mandi and the Kullu valley to Manali.', 5500, 7500, 12000, NULL, NULL, 400),
('plib_hp_04', 'Himachal Pradesh', 'SIGHTSEEING', 'Manali local sightseeing', 'Manali', NULL, NULL, 30, 6, 'Manali: temples and old town', 'Visit Hadimba Devi Temple, Vashisht hot springs, the Tibetan Monastery and Old Manali.', 2200, 3000, 4800, NULL, NULL, 410),
('plib_hp_05', 'Himachal Pradesh', 'SIGHTSEEING', 'Solang Valley and Atal Tunnel', 'Manali', NULL, NULL, 70, 8, 'Solang Valley and Atal Tunnel', 'Drive to Solang Valley for snow and adventure sports, then through the Atal Tunnel to Sissu in Lahaul.', 3000, 4000, 6500, NULL, NULL, 420),
('plib_hp_06', 'Himachal Pradesh', 'TRANSFER', 'Manali to Chandigarh by car', 'Manali', 'Hotel in Manali', 'Chandigarh', 310, 8, 'Manali to Chandigarh', 'Drive back to Chandigarh for your onward journey.', 6000, 8000, 13000, NULL, NULL, 430),
('plib_hp_07', 'Himachal Pradesh', 'TRANSFER', 'Dharamshala (Gaggal) Airport to Hotel', 'Dharamshala', 'Gaggal Airport', 'Hotel in Dharamshala', 15, 0.5, 'Arrive in Dharamshala', 'Our driver meets you at Gaggal airport and takes you to your hotel in Dharamshala or McLeod Ganj.', 1000, 1500, 2800, NULL, NULL, 440),
('plib_hp_08', 'Himachal Pradesh', 'SIGHTSEEING', 'Dharamshala and McLeod Ganj sightseeing', 'Dharamshala', NULL, NULL, 40, 6, 'Dharamshala and McLeod Ganj', 'See the Dalai Lama Temple, Bhagsu Nag waterfall, St. John in the Wilderness church and the HPCA cricket stadium.', 2200, 3000, 4800, NULL, NULL, 450),
('plib_jk_01', 'Jammu & Kashmir', 'TRANSFER', 'Srinagar Airport to Hotel or Houseboat', 'Srinagar', 'Srinagar Airport', 'Hotel or houseboat in Srinagar', 15, 1, 'Arrive in Srinagar', 'Our driver meets you at Srinagar airport and takes you to your hotel or houseboat on Dal Lake.', 1200, 1800, 3200, NULL, NULL, 460),
('plib_jk_02', 'Jammu & Kashmir', 'SIGHTSEEING', 'Srinagar local sightseeing', 'Srinagar', NULL, NULL, 40, 6, 'Srinagar: Mughal gardens', 'Visit the Mughal gardens of Nishat Bagh, Shalimar Bagh and Chashme Shahi, and the Shankaracharya Temple.', 2200, 3000, 4800, NULL, NULL, 470),
('plib_jk_03', 'Jammu & Kashmir', 'ACTIVITY', 'Dal Lake shikara ride (1 hour)', 'Srinagar', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 400, 200, 480),
('plib_jk_04', 'Jammu & Kashmir', 'SIGHTSEEING', 'Srinagar to Gulmarg day trip', 'Gulmarg', NULL, NULL, 110, 9, 'Gulmarg day trip', 'Drive to Gulmarg, the meadow of flowers, and ride the Gulmarg Gondola. Return to Srinagar in the evening.', 3200, 4200, 7000, NULL, NULL, 490),
('plib_jk_05', 'Jammu & Kashmir', 'ACTIVITY', 'Gulmarg Gondola phase 1', 'Gulmarg', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, 850, 850, 500),
('plib_jk_06', 'Jammu & Kashmir', 'SIGHTSEEING', 'Srinagar to Pahalgam day trip', 'Pahalgam', NULL, NULL, 190, 10, 'Pahalgam day trip', 'Drive past saffron fields and Avantipur ruins to Pahalgam in the Lidder valley. Local union cabs to Aru, Betaab and Chandanwari are paid there.', 3800, 5000, 8000, NULL, NULL, 510),
('plib_jk_07', 'Jammu & Kashmir', 'SIGHTSEEING', 'Srinagar to Sonamarg day trip', 'Sonamarg', NULL, NULL, 160, 9, 'Sonamarg day trip', 'Drive along the Sindh river to Sonamarg, the meadow of gold, with views of the Thajiwas glacier.', 3500, 4600, 7500, NULL, NULL, 520),
('plib_jk_08', 'Jammu & Kashmir', 'TRANSFER', 'Jammu to Katra by car', 'Jammu', 'Jammu', 'Hotel in Katra', 50, 1.5, 'Jammu to Katra', 'Drive to Katra, the base for the Vaishno Devi yatra, and check in.', 1800, 2500, 4200, NULL, NULL, 530),
('plib_jk_09', 'Jammu & Kashmir', 'TRANSFER', 'Jammu to Srinagar by car', 'Jammu', 'Jammu', 'Hotel in Srinagar', 250, 8, 'Jammu to Srinagar', 'Drive through the Banihal tunnel into the Kashmir valley to Srinagar.', 6000, 8000, 13000, NULL, NULL, 540),
('plib_lad_01', 'Leh Ladakh', 'TRANSFER', 'Leh Airport to Hotel', 'Leh', 'Leh Airport', 'Hotel in Leh', 5, 0.5, 'Arrive in Leh: rest day', 'Our driver meets you at Leh airport and takes you to your hotel. Rest all day to get used to the altitude of 3,500 m.', 1000, 1500, 2800, NULL, NULL, 550),
('plib_lad_02', 'Leh Ladakh', 'SIGHTSEEING', 'Leh local sightseeing', 'Leh', NULL, NULL, 60, 7, 'Leh: palace and monasteries', 'Visit Shanti Stupa, Leh Palace, Hall of Fame, Gurudwara Pathar Sahib and Magnetic Hill, and the Indus-Zanskar confluence.', 2800, 3500, 5500, NULL, NULL, 560),
('plib_lad_03', 'Leh Ladakh', 'SIGHTSEEING', 'Leh to Nubra Valley via Khardung La', 'Leh', NULL, NULL, 160, 7, 'Leh to Nubra Valley', 'Cross Khardung La, one of the world''s highest motorable passes, to Nubra Valley. See Diskit Monastery and the sand dunes of Hunder.', 6500, 8000, 13000, NULL, NULL, 570),
('plib_lad_04', 'Leh Ladakh', 'SIGHTSEEING', 'Leh to Pangong Lake', 'Leh', NULL, NULL, 225, 7, 'Leh to Pangong Lake', 'Drive over Chang La pass to Pangong Tso, the high-altitude lake whose waters change colour through the day.', 7500, 9000, 14500, NULL, NULL, 580),
('plib_lad_05', 'Leh Ladakh', 'TRANSFER', 'Nubra to Pangong via Shyok road', 'Nubra', 'Nubra Valley', 'Pangong Lake', 180, 7, 'Nubra to Pangong', 'Drive along the Shyok river road from Nubra straight to Pangong Lake.', 7000, 8500, 13500, NULL, NULL, 590),
('plib_lad_06', 'Leh Ladakh', 'ACTIVITY', 'Bactrian camel ride at Hunder', 'Nubra', NULL, NULL, NULL, 0.5, NULL, NULL, NULL, NULL, NULL, 500, 500, 600),
('plib_lad_07', 'Leh Ladakh', 'TRANSFER', 'Hotel to Leh Airport', 'Leh', 'Hotel in Leh', 'Leh Airport', 5, 0.5, 'Departure from Leh', 'After breakfast, transfer to Leh airport for your onward flight.', 1000, 1500, 2800, NULL, NULL, 610),
('plib_raj_01', 'Rajasthan', 'TRANSFER', 'Jaipur Airport to Hotel', 'Jaipur', 'Jaipur Airport', 'Hotel in Jaipur', 15, 1, 'Arrive in Jaipur', 'Our driver meets you at Jaipur airport and takes you to your hotel.', 1200, 1800, 3200, NULL, NULL, 620),
('plib_raj_02', 'Rajasthan', 'TRANSFER', 'Jaipur to Jodhpur by car', 'Jaipur', 'Hotel in Jaipur', 'Hotel in Jodhpur', 340, 6, 'Jaipur to Jodhpur', 'Drive west to Jodhpur, the Blue City.', 6500, 8500, 14000, NULL, NULL, 630),
('plib_raj_03', 'Rajasthan', 'SIGHTSEEING', 'Jodhpur sightseeing', 'Jodhpur', NULL, NULL, 40, 6, 'Jodhpur: the Blue City', 'Visit Mehrangarh Fort, Jaswant Thada and Umaid Bhawan Palace museum, and walk the Clock Tower market.', 2200, 3000, 4800, NULL, NULL, 640),
('plib_raj_04', 'Rajasthan', 'TRANSFER', 'Jodhpur to Jaisalmer by car', 'Jodhpur', 'Hotel in Jodhpur', 'Hotel in Jaisalmer', 285, 5, 'Jodhpur to Jaisalmer', 'Drive into the Thar desert to Jaisalmer, the Golden City.', 6000, 8000, 13000, NULL, NULL, 650),
('plib_raj_05', 'Rajasthan', 'SIGHTSEEING', 'Jaisalmer sightseeing and Sam dunes', 'Jaisalmer', NULL, NULL, 100, 9, 'Jaisalmer: fort and desert', 'See the living Jaisalmer Fort, Patwon ki Haveli and Gadisar Lake, then drive to the Sam sand dunes for sunset.', 2800, 3800, 6000, NULL, NULL, 660),
('plib_raj_06', 'Rajasthan', 'ACTIVITY', 'Camel safari at Sam dunes', 'Jaisalmer', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 600, 400, 670),
('plib_raj_07', 'Rajasthan', 'TRANSFER', 'Jodhpur to Udaipur via Ranakpur', 'Jodhpur', 'Hotel in Jodhpur', 'Hotel in Udaipur', 260, 6, 'Jodhpur to Udaipur via Ranakpur', 'Drive to Udaipur, stopping at the marble Jain temples of Ranakpur.', 5500, 7500, 12000, NULL, NULL, 680),
('plib_raj_08', 'Rajasthan', 'SIGHTSEEING', 'Udaipur sightseeing', 'Udaipur', NULL, NULL, 40, 7, 'Udaipur: City of Lakes', 'Visit the City Palace, Jagdish Temple, Saheliyon ki Bari and Fateh Sagar Lake.', 2300, 3200, 5000, NULL, NULL, 690),
('plib_raj_09', 'Rajasthan', 'ACTIVITY', 'Lake Pichola boat ride', 'Udaipur', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 500, 300, 700),
('plib_raj_10', 'Rajasthan', 'TRANSFER', 'Jaipur to Pushkar by car', 'Jaipur', 'Hotel in Jaipur', 'Hotel in Pushkar', 150, 3, 'Jaipur to Pushkar', 'Drive to Pushkar, visit the Brahma Temple and walk the ghats of Pushkar Lake.', 3500, 5000, 8000, NULL, NULL, 710),
('plib_uk_01', 'Uttarakhand', 'TRANSFER', 'Dehradun (Jolly Grant) Airport to Rishikesh', 'Dehradun', 'Jolly Grant Airport', 'Hotel in Rishikesh', 20, 0.75, 'Arrive in Rishikesh', 'Our driver meets you at Dehradun airport and takes you to your hotel in Rishikesh.', 1200, 1800, 3200, NULL, NULL, 720),
('plib_uk_02', 'Uttarakhand', 'TRANSFER', 'Haridwar to Rishikesh by car', 'Haridwar', 'Haridwar', 'Hotel in Rishikesh', 25, 1, 'Haridwar to Rishikesh', 'Drive to Rishikesh, the yoga capital of the world, and check in.', 1200, 1800, 3200, NULL, NULL, 730),
('plib_uk_03', 'Uttarakhand', 'SIGHTSEEING', 'Haridwar and Rishikesh sightseeing', 'Rishikesh', NULL, NULL, 60, 8, 'Haridwar and Rishikesh', 'Walk across Ram Jhula and Lakshman Jhula, visit the Beatles Ashram, and watch the evening Ganga Aarti at Har Ki Pauri in Haridwar.', 2500, 3500, 5500, NULL, NULL, 740),
('plib_uk_04', 'Uttarakhand', 'ACTIVITY', 'Ganga river rafting (16 km)', 'Rishikesh', NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, 1000, 1000, 750),
('plib_uk_05', 'Uttarakhand', 'TRANSFER', 'Dehradun to Mussoorie by car', 'Dehradun', 'Dehradun', 'Hotel in Mussoorie', 35, 1.5, 'Dehradun to Mussoorie', 'Drive up to Mussoorie, the queen of the hills, and check in.', 1800, 2500, 4200, NULL, NULL, 760),
('plib_uk_06', 'Uttarakhand', 'SIGHTSEEING', 'Mussoorie sightseeing', 'Mussoorie', NULL, NULL, 50, 6, 'Mussoorie', 'Visit Kempty Falls, Gun Hill, Company Garden and walk the Mall Road.', 2300, 3200, 5000, NULL, NULL, 770),
('plib_uk_07', 'Uttarakhand', 'TRANSFER', 'Kathgodam to Nainital by car', 'Kathgodam', 'Kathgodam railway station', 'Hotel in Nainital', 35, 1.5, 'Kathgodam to Nainital', 'Our driver meets you at Kathgodam station and takes you up to Nainital.', 1800, 2500, 4200, NULL, NULL, 780),
('plib_uk_08', 'Uttarakhand', 'SIGHTSEEING', 'Nainital lake tour', 'Nainital', NULL, NULL, 60, 7, 'Nainital and the lakes', 'See Naini Lake and the Naina Devi Temple, then drive to Bhimtal, Sattal and Naukuchiatal.', 2300, 3200, 5000, NULL, NULL, 790),
('plib_uk_09', 'Uttarakhand', 'TRANSFER', 'Nainital to Jim Corbett by car', 'Nainital', 'Hotel in Nainital', 'Resort in Jim Corbett', 65, 2, 'Nainital to Jim Corbett', 'Drive to Jim Corbett National Park, India''s oldest national park, and check in to your resort.', 2500, 3500, 5500, NULL, NULL, 800),
('plib_uk_10', 'Uttarakhand', 'ACTIVITY', 'Jim Corbett jeep safari (per seat)', 'Jim Corbett', NULL, NULL, NULL, 4, 'Jim Corbett jungle safari', 'Go on a jeep safari in Jim Corbett National Park, home to tigers, elephants and hundreds of bird species.', NULL, NULL, NULL, 1500, 1500, 810);

-- @down
ALTER TABLE supplier_services DROP COLUMN library_item_id;
DROP INDEX IF EXISTS idx_package_library_items_region;
DROP TABLE IF EXISTS package_library_items;
