ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_instructions VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS drop_instructions VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS flight_number VARCHAR(20);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS flight_arrival_time VARCHAR(20);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS terminal_gate VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS promo_code VARCHAR(50);
